### ISSUE TITLE
How to download the IB futures data for ES

### ISSUE THREAD

**Issue by leochirag** [busygin/ib_data_loader#1]
Hi,

I was trying to use your script for downloading the futures data for ES and am getting an error :

""main.py", line 10, in main
    symbol = sys.argv[5]
IndexError: list index out of range"

How do I exactly use this script ? Any help would be much appreciated.

Thanks.
Chirag

**Comment by busygin** [comment]
How did you get symbol = sys.argv[5]?
main.py line 10 is symbol = sys.argv[1]
Have you edited the file for some reason?

**Comment by leochirag** [comment]
Hi,

Thanks for your reply. No, I haven't edited the file at all. These lines exist in the main.py.
See the below screenshot for reference.

<img width="786" alt="screen shot 2018-07-12 at 6 09 33 pm" src="https://user-images.githubusercontent.com/18371048/42664133-c3e54d22-85fe-11e8-9700-5e64d41418dc.png">

**Comment by leochirag** [comment]
The above main.py is running successfully now but nothing is getting populated in the ".bars" file. 

Can someone please help me with this ?

<img width="489" alt="screen shot 2018-07-16 at 11 52 45 am" src="https://user-images.githubusercontent.com/18371048/42772054-cd761158-88ee-11e8-812f-b687eb75de14.png">

**Comment by busygin** [comment]
You have to provide arguments in the command line. Please read the readme file.

**Comment by leochirag** [comment]
If I include those sys.argv lines then I get the "IndexError: list index out of range", so I removed them and provided arguments directly into the code for symbol, security_type, etc.

**Comment by busygin** [comment]
1. The error message you provided at the very beginning is not consistent with the code (which can be seen at your first screenshot). You can clearly see on your own screenshot that line 10 is:
`symbol = sys.argv[1]`
Nevertheless, you insist that your error message was:
"main.py", line 10, in main
symbol = sys.argv[5]
IndexError: list index out of range

Do you see that it's 1 in the code and 5 in the error message? How can it be if you didn't modify either the code or the error message itself?

2. IB holds the bar data only for a year, IIRC. Of course, you won't get data for 2015 as you have tried.

For the record: this code is provided AS IS. I give no guarantee of its correctness or usefulness for any purpose.

If it doesn't work for you, read the IB documentation yourself and develop your own code.
